#=================================================
# Description: 86x64 Openwrt Autobuild
# Lisence: MIT
# Author: chensir
#=================================================
name: Build Lean's OpenWrt for x86_64

on:
  release:
    types: [published]
  push:
    branches:
      - master
    paths:
      - "x86_64.config"
  schedule:
    - cron: 0 0 * * 1
  watch:
    types: [started]
  workflow_dispatch:
    inputs:
      logs:
        description: 'You can input logs here'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          set +e 
          docker rmi `docker images -q`
          echo "Deleting files, please wait ..."
          sudo rm -rf \
          /usr/share/dotnet \
          /etc/mysql \
          /etc/php
          sudo -E apt-get -y purge \
          azure-cli \
          ghc* \
          zulu* \
          hhvm \
          llvm* \
          firefox \
          google* \
          dotnet* \
          powershell \
          openjdk* \
          mysql* \
          php*
          sudo -E apt-get update
          sudo -E apt-get -y install ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: Clone source code
        env:
          REPO_URL: https://github.com/coolsnowwolf/lede
          REPO_BRANCH: master
        run: git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

      - name: add custom source
        run: |
          cd openwrt
          sed -i "/helloworld/d" "feeds.conf.default"
          echo "src-git helloworld https://github.com/fw876/helloworld.git" >> "feeds.conf.default"

      - name: Update & install feeds
        run: cd openwrt && ./scripts/feeds update -a && ./scripts/feeds install -a

      - name: Load custom configuration
        env:
          CONFIG_FILE: "x86_64.config"
          DIY_SH: "diy.sh"
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x $DIY_SH
          cd openwrt
          echo 'CONFIG_KERNEL_BUILD_USER="chensir"' >> ./.config
          echo "CONFIG_GRUB_TITLE=\"OpenWrt AutoBuild by chensir-$Date_and_RunNumber\"" >> ./.config
          echo "OpenWrt AutoBuild by chensir - $Date_and_RunNumber" >> package/base-files/files/etc/banner
          ../$DIY_SH
          make defconfig

      # - name: SSH connection to Actions
      #   uses: P3TERX/debugger-action@master

      - name: Download package
        run: |
          cd openwrt && make download -j$(($(nproc)+1))
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Multi-thread compile
        run: |
          cd openwrt
          echo -e "$(($(nproc)+1)) thread compile"
          make -j$(($(nproc)+1))

      - name: Single-thread compile
        if: failure()
        run: |
          cd openwrt
          make -j1 V=s

      - name: Upload bin directory
        uses: actions/upload-artifact@main
        if: always()
        with:
          name: OpenWrt_x86_64_bin-${{ env.Date_and_RunNumber }}
          path: openwrt/bin

      - name: Remove packages
        if: always()
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          echo "Firmware_path=$(pwd)" >> $GITHUB_ENV
          
          
      - name: Upload firmware to Artifact
        uses: actions/upload-artifact@main
        if: always()
        with:
          name: OpenWrt-x86_64-Firmware-${{ env.Date_and_RunNumber }}
          path: ${{ env.Firmware_path }}

      - name: Publish release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: openwrt/bin/targets/x86/x86_64/*
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASES_DEPLOY_TOKEN }}
